[manifest]
version = "1.0.0"
dump_lua = true
priority = 10000000

# Override pokedex
[[patches]]
[patches.pattern]
target = '''=[SMODS Pokermon "pokeui.lua"]'''
pattern = '''and (target.config.center.stage or target.config.center.poke_multi_item) then'''
position = "after"
payload = '''
if true then return Glossary.show_card_info(target) end
'''
match_indent = true
