[manifest]
version = "1.0.0"
dump_lua = true
priority = 10000000

# Mouse listener
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.mousepressed(x, y, button, touch)'''
position = "after"
payload = '''
if button == 2 then
	Glossary.open(G.CONTROLLER.hovering.target)
end
'''
match_indent = true
