[manifest]
version = "1.0.0"
dump_lua = true
priority = 10000000

# Mouse listener
[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''function love.mousepressed(x, y, button, touch)'''
position = "after"
payload = '''
if button == 2 then
    local hovered_target = G.CONTROLLER.hovering.target
	if hovered_target then
		if hovered_target.is and hovered_target:is(Card) then
			hovered_target:stop_hover()
			Glossary.show_card_info(hovered_target, "card", hovered_target)
		elseif hovered_target.config and hovered_target.config.tag then
			hovered_target:stop_hover()
			Glossary.show_tag_info(hovered_target.config.tag, "tag", hovered_target.config.tag)
		elseif
			hovered_target.config
			and hovered_target.config.ref_table
			and hovered_target.config.ref_table.config
			and hovered_target.config.ref_table.config.tag
		then
			hovered_target:stop_hover()
			Glossary.show_tag_info(hovered_target.config.ref_table.config.tag, "tag", hovered_target.config.ref_table.config.tag)
		end
	end
end
'''
match_indent = true
