[manifest]
version = "1.0.0"
dump_lua = true
priority = 10000000

# Process info queue from generate_card_ui
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''for _, v in ipairs(info_queue) do'''
position = "before"
payload = '''
local glossary_should_finish = false
if Glossary.processing.current_request and not Glossary.processing.current_request.started then
    glossary_should_finish = true
    Glossary.processing.current_request.started = true
    local context = Glossary.processing.current_request.context

    context.AUT = full_UI_table
    context.info_queue = info_queue

    Glossary.processing.process_before_context(context)
    Glossary.processing.process_individual_context(context)
end
'''
match_indent = true

# Request after processing request
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''return full_UI_table'''
position = "before"
payload = '''
if glossary_should_finish then
    Glossary.processing.current_request.can_finish = true
end
'''
match_indent = true
